version: "3.8"
services:
  catalogdb: 
    image: mongo
  basketdb:
    image: redis
  discountdb:
    image: postgres
  identitydb:
    image: mcr.microsoft.com/azure-sql-edge
  orderdb:
    image: mcr.microsoft.com/azure-sql-edge
  rabbitmq:
    image: rabbitmq:rabbitmq:3.11.9-management
volumes:
  catalogdb_volume:
  discountdb_volume:
  identitydb_volume:
  orderdb_volume:
